/**
 * SCRIPT CHẠY 1 LẦN (không phải onEdit) — KHÔNG dán vào file onEdit_NgayTest.gs.
 * -------------------------------------------------------------------------
 * Tạo Test Case cho các dòng 05_Lỗi_Tester (211-234) đang thiếu TC_ID(s):
 *  - Không có TC tổng quát nào (TC_UI_001-011, TC_IC_001-006...) khớp DS_ID của
 *    24 dòng này, nên mỗi dòng được tạo 1 TC riêng theo đúng khuôn mẫu có sẵn
 *    trong sheet ("Xác minh lỗi BUG_XXX", xem TC_UI_012, TC_FUNC_008...).
 *  - Thêm 24 dòng mới vào cuối 04_Test_Cases (nối tiếp TC_UI_086 / TC_FUNC_044 /
 *    TC_RESP_015 hiện có -> TC_UI_087..105, TC_FUNC_045-046, TC_RESP_016-018).
 *  - Ghi TC_ID tương ứng vào cột G (TC_ID(s)) của từng dòng 05_Lỗi_Tester.
 *
 * CÁCH CHẠY:
 *  1. Vào Tiện ích mở rộng → Apps Script (cùng project với onEdit_NgayTest.gs).
 *  2. Tạo FILE MỚI (không ghi đè file onEdit) tên tuỳ ý (vd: create_missing_testcases.gs),
 *     dán toàn bộ nội dung này vào.
 *  3. Trong thanh công cụ, chọn hàm "createMissingTestCases" → bấm Run (▶).
 *  4. Cấp quyền nếu được hỏi lần đầu.
 *  5. Kiểm tra 04_Test_Cases (24 dòng mới cuối bảng) và 05_Lỗi_Tester (cột
 *     TC_ID(s) dòng 211-234) đã được điền.
 *  Script AN TOÀN khi chạy nhiều lần: dòng nào ở 05_Lỗi_Tester đã có TC_ID rồi
 *  thì bị bỏ qua, không tạo trùng.
 */

var NEW_TEST_CASES = [
  { srcRow: 211, tcId: 'TC_UI_087', reqIds: '', ycLienQuan: 'Thiết kế page này theo thiết kế Figma', dsIds: 'DS_11', trangLienQuan: 'DS_11: Trang Cộng đồng chi tiết người đăng', tenTC: 'Xác minh lỗi BUG_021', moTaTC: 'Kiểm tra Trang Cộng đồng chi tiết người đăng. Hiện tượng cần xác minh: Thiếu page', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Cộng đồng chi tiết người đăng; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_021.', ketQua: 'Có thể xem được page chi tiết', loaiTest: 'UI/UX', mucDo: 'High', thietBi: 'Desktop, Mobile, Tablet', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_021', tester: 'Mr. Ẩn' },
  { srcRow: 212, tcId: 'TC_UI_088', reqIds: '', ycLienQuan: 'Thiết kế page này theo thiết kế Figma', dsIds: 'DS_12', trangLienQuan: 'DS_12: Trang Cộng đồng chi tiết nhà tuyển dụng', tenTC: 'Xác minh lỗi BUG_022', moTaTC: 'Kiểm tra Trang Cộng đồng chi tiết nhà tuyển dụng. Hiện tượng cần xác minh: Thiếu page', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Cộng đồng chi tiết nhà tuyển dụng; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_022.', ketQua: 'Có thể xem được page chi tiết', loaiTest: 'UI/UX', mucDo: 'High', thietBi: 'Desktop, Mobile, Tablet', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_022', tester: 'Mr. Ẩn' },
  { srcRow: 213, tcId: 'TC_UI_089', reqIds: 'YC_33', ycLienQuan: 'YC_33: Thiết kế theo Figma', dsIds: 'DS_36', trangLienQuan: 'DS_36: Trang Giới thiệu bản thân', tenTC: 'Xác minh lỗi BUG_LO_018', moTaTC: 'Kiểm tra Trang Giới thiệu bản thân. Hiện tượng cần xác minh: Không phải mở popup mà là 1 page riêng(Nếu chuyển sang dùng PopUp thì đồng bộ với các page tương tự)', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Giới thiệu bản thân; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_LO_018.', ketQua: 'Ít nhất phải có 2 phần nhập(tự nhập, và A.I gợi ý)', loaiTest: 'UI/UX', mucDo: 'High', thietBi: 'Desktop, Mobile, Tablet', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_LO_018', tester: 'Mr. Ẩn' },
  { srcRow: 214, tcId: 'TC_UI_090', reqIds: 'YC_31', ycLienQuan: 'YC_31: Kỹ năng nghề nghiệp', dsIds: 'DS_37', trangLienQuan: 'DS_37: Trang Kỹ năng nghề nghiệp', tenTC: 'Xác minh lỗi BUG_UI_091', moTaTC: 'Kiểm tra Trang Kỹ năng nghề nghiệp. Hiện tượng cần xác minh: - Button sai với thiết kế figma và cũng không đồng nhất với các page khác.\n-  Select Box đồng nhất với các page khác or đúng theo Figma', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Kỹ năng nghề nghiệp; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_091.', ketQua: '- Đồng bộ hoặc đúng thiết kế', loaiTest: 'UI/UX', mucDo: 'Medium', thietBi: 'Desktop, Tablet', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_UI_091', tester: 'Mr. Ẩn' },
  { srcRow: 215, tcId: 'TC_RESP_016', reqIds: 'YC_31', ycLienQuan: 'YC_31: Kỹ năng nghề nghiệp', dsIds: 'DS_37', trangLienQuan: 'DS_37: Trang Kỹ năng nghề nghiệp', tenTC: 'Xác minh lỗi BUG_UI_MOB_017', moTaTC: 'Kiểm tra Trang Kỹ năng nghề nghiệp. Hiện tượng cần xác minh: - Hiện đang hiển thị dạng page, cần phải chuyển thành popup', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Kỹ năng nghề nghiệp; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_MOB_017.', ketQua: '- Hiển thị dạng popup và đúng theo thiết kế Figma', loaiTest: 'Responsive', mucDo: 'High', thietBi: 'Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_UI_MOB_017', tester: 'Mr. Ẩn' },
  { srcRow: 216, tcId: 'TC_RESP_017', reqIds: 'YC_34', ycLienQuan: 'YC_34: Thêm chứng nhận và giải thưởng.', dsIds: 'DS_38', trangLienQuan: 'DS_38: Trang Chứng nhận/Giải thưởng', tenTC: 'Xác minh lỗi BUG_UI_MOB_018', moTaTC: 'Kiểm tra Trang Chứng nhận/Giải thưởng. Hiện tượng cần xác minh: - Thiết kế lại page này theo đúng thiết kế Figma', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Chứng nhận/Giải thưởng; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_MOB_018.', ketQua: '- Thiết kế lại page này theo đúng thiết kế Figma', loaiTest: 'Responsive', mucDo: 'High', thietBi: 'Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_UI_MOB_018', tester: 'Mr. Ẩn' },
  { srcRow: 217, tcId: 'TC_UI_091', reqIds: 'YC_35', ycLienQuan: 'YC_35: Thêm chứng nhận và giải thưởng.', dsIds: 'DS_39', trangLienQuan: 'DS_39: Trang Chứng nhận/Giải thưởng', tenTC: 'Xác minh lỗi BUG_UI_092', moTaTC: 'Kiểm tra Trang Chứng nhận/Giải thưởng. Hiện tượng cần xác minh: - Sai thiết kế Button, Layout(or phải đồng nhất như các page khác)', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Chứng nhận/Giải thưởng; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_092.', ketQua: '- Button, Layout đúng thiết kế (or phải đồng nhất như các page khác)', loaiTest: 'UI/UX', mucDo: 'High', thietBi: 'Desktop, Tablet', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_UI_092', tester: 'Mr. Ẩn' },
  { srcRow: 218, tcId: 'TC_UI_092', reqIds: 'YC_35', ycLienQuan: 'YC_35: Đính kèm hình ảnh minh hoạ.', dsIds: 'DS_39', trangLienQuan: 'DS_39: Trang Hình ảnh liên quan', tenTC: 'Xác minh lỗi BUG_UI_093', moTaTC: 'Kiểm tra Trang Hình ảnh liên quan. Hiện tượng cần xác minh: - Đang hiển thị dạng popup\n- Icon xóa ảnh chưa đúng\n- Thiết kế hiển thị ảnh đang sai', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Hình ảnh liên quan; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_093.', ketQua: '- Hiển thị dạng page\n- Icon xóa ảnh đúng thiết kế\n- Layout dạng ngang từng dòng cho mỗi Dự án', loaiTest: 'UI/UX', mucDo: 'High', thietBi: 'Desktop, Mobile, Tablet', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_UI_093', tester: 'Mr. Ẩn' },
  { srcRow: 219, tcId: 'TC_UI_093', reqIds: 'YC_37', ycLienQuan: 'YC_37: Xem việc làm và bài đăng đã lưu.', dsIds: 'DS_44', trangLienQuan: 'DS_44: Trang Danh sách đã lưu', tenTC: 'Xác minh lỗi BUG_UI_094', moTaTC: 'Kiểm tra Trang Danh sách đã lưu. Hiện tượng cần xác minh: Sai màu, icon, layout,...', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Danh sách đã lưu; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_094.', ketQua: 'Giống với thiết kế Figma', loaiTest: 'UI/UX', mucDo: 'Critical', thietBi: 'Desktop, Tablet', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_UI_094', tester: 'Mr. Ẩn' },
  { srcRow: 220, tcId: 'TC_RESP_018', reqIds: 'YC_37', ycLienQuan: 'YC_37: Xem việc làm và bài đăng đã lưu.', dsIds: 'DS_44', trangLienQuan: 'DS_44: Trang Danh sách đã lưu', tenTC: 'Xác minh lỗi BUG_UI_MOB_019', moTaTC: 'Kiểm tra Trang Danh sách đã lưu. Hiện tượng cần xác minh: - Thiết kế lại page này theo đúng thiết kế Figma', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Danh sách đã lưu; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_MOB_019.', ketQua: 'Giống với thiết kế Figma', loaiTest: 'Responsive', mucDo: 'High', thietBi: 'Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_UI_MOB_019', tester: 'Mr. Ẩn' },
  { srcRow: 221, tcId: 'TC_FUNC_045', reqIds: 'YC_71', ycLienQuan: 'YC_71: Quản lý theo vị trí ứng tuyển', dsIds: 'DS_57', trangLienQuan: 'DS_57: Vị trí ứng tuyển', tenTC: 'Xác minh lỗi BUG_FUNC_046', moTaTC: 'Kiểm tra Vị trí ứng tuyển. Hiện tượng cần xác minh: Đang hiển thị tiêu đề tin, không phải vị trí ứng tuyển\nCác trường theo dõi đang sai yêu cầu', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Vị trí ứng tuyển; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_FUNC_046.', ketQua: 'Có thể theo dõi vị trí ứng tuyển, các thông tin cần theo dõi đúng với yêu cầu thiết kế', loaiTest: 'Functional', mucDo: 'Critical', thietBi: 'Desktop, Tablet', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_FUNC_046', tester: 'Mr. Ẩn' },
  { srcRow: 222, tcId: 'TC_UI_094', reqIds: 'YC_71', ycLienQuan: 'YC_71: Quản lý theo vị trí ứng tuyển', dsIds: 'DS_53', trangLienQuan: 'DS_53: Trang Hiệu quả tuyển dụng', tenTC: 'Xác minh lỗi BUG_UI_095', moTaTC: 'Kiểm tra Trang Hiệu quả tuyển dụng. Hiện tượng cần xác minh: Title thiếu border-bottom(Mỗi item đều có border-bottom)', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Hiệu quả tuyển dụng; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_095.', ketQua: 'Đúng thiết kế Figma', loaiTest: 'UI/UX', mucDo: 'Low', thietBi: 'Desktop, Tablet, Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_UI_095', tester: 'Mr. Ẩn' },
  { srcRow: 223, tcId: 'TC_UI_095', reqIds: 'YC_79', ycLienQuan: 'YC_79: Dashboard hiệu quả tuyển dụng', dsIds: 'DS_53', trangLienQuan: 'DS_53: Trang Hiệu quả tuyển dụng', tenTC: 'Xác minh lỗi BUG_UI_MOB_020', moTaTC: 'Kiểm tra Trang Hiệu quả tuyển dụng. Hiện tượng cần xác minh: Xem lại background của biểu đồ', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Hiệu quả tuyển dụng; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_MOB_020.', ketQua: 'Hiển thị và hoạt động đúng theo thiết kế/yêu cầu đã duyệt.', loaiTest: 'UI/UX', mucDo: 'Medium', thietBi: 'Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_UI_MOB_020', tester: 'Mr. Ẩn' },
  { srcRow: 224, tcId: 'TC_UI_096', reqIds: 'YC_79', ycLienQuan: 'YC_79: Dashboard hiệu quả tuyển dụng', dsIds: 'DS_53', trangLienQuan: 'DS_53: Trang Hiệu quả tuyển dụng', tenTC: 'Xác minh lỗi BUG_UI_096', moTaTC: 'Kiểm tra Trang Hiệu quả tuyển dụng. Hiện tượng cần xác minh: Xem lại background của biểu đồ và Boder của bảng chi tiết', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Hiệu quả tuyển dụng; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_096.', ketQua: 'Hiển thị và hoạt động đúng theo thiết kế/yêu cầu đã duyệt.', loaiTest: 'UI/UX', mucDo: 'Medium', thietBi: 'Desktop, Tablet', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-24', bugId: 'BUG_UI_096', tester: 'Mr. Ẩn' },
  { srcRow: 225, tcId: 'TC_UI_097', reqIds: 'YC_74', ycLienQuan: 'YC_74: Thiết kế giống với Figma', dsIds: 'DS_59', trangLienQuan: 'DS_59: Vị trí ứng tuyển- Hồ sơ ứng tuyển & Đề xuất', tenTC: 'Xác minh lỗi BUG_UI_097', moTaTC: 'Kiểm tra Vị trí ứng tuyển- Hồ sơ ứng tuyển & Đề xuất. Hiện tượng cần xác minh: Xem lại thiết kế hoặc giải thích', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Vị trí ứng tuyển- Hồ sơ ứng tuyển & Đề xuất; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_097.', ketQua: 'Đi đến 1 quyết định cuối cùng về thiết kế', loaiTest: 'UI/UX', mucDo: 'Medium', thietBi: 'Desktop, Tablet, Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-25', bugId: 'BUG_UI_097', tester: 'Mr. Ẩn' },
  { srcRow: 226, tcId: 'TC_FUNC_046', reqIds: 'YC_71', ycLienQuan: 'YC_71: Nhóm ứng viên theo vị trí và kết quả.', dsIds: 'DS_57', trangLienQuan: 'DS_57: Vị trí ứng tuyển', tenTC: 'Xác minh lỗi BUG_FUNC_047', moTaTC: 'Kiểm tra Vị trí ứng tuyển. Hiện tượng cần xác minh: Nút quay lại đang điều hướng sai bước trước đó', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Vị trí ứng tuyển; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_FUNC_047.', ketQua: 'Đúng mô tả yều cầu', loaiTest: 'Functional', mucDo: 'High', thietBi: 'Desktop, Tablet, Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-25', bugId: 'BUG_FUNC_047', tester: 'Mr. Ẩn' },
  { srcRow: 227, tcId: 'TC_UI_098', reqIds: 'YC_18, YC_19', ycLienQuan: 'YC_18, YC_19: Tìm việc theo từ khoá và địa điểm\nBộ lọc tìm kiếm nâng cao', dsIds: 'DS_04', trangLienQuan: 'DS_04: Trang Tìm kiếm', tenTC: 'Xác minh lỗi BUG_UI_098', moTaTC: 'Kiểm tra Trang Tìm kiếm. Hiện tượng cần xác minh: Body nhỏ, button tìm kiếm thô, bộ lọc trình bày quá lớn', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Tìm kiếm; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_098.', ketQua: 'Thiết kế lại cho phù hợp trên Mobile\n- Button tìm kiếm: bỏ text đi\n- Bộ lọc thu gọn hoặc design gọn lại\n- Body mở rộng ra', loaiTest: 'UI/UX', mucDo: 'Critical', thietBi: 'Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-25', bugId: 'BUG_UI_098', tester: 'Mr. Ẩn' },
  { srcRow: 228, tcId: 'TC_UI_099', reqIds: '', ycLienQuan: 'Boder tách rời từng item, đồng thời cũng bỏ luôn trường "tỉnh" đi', dsIds: 'DS_03', trangLienQuan: 'DS_03: Trang DN địa phương chi tiết', tenTC: 'Xác minh lỗi BUG_UI_099', moTaTC: 'Kiểm tra Trang DN địa phương chi tiết. Hiện tượng cần xác minh: Boder tách rời từng item, đồng thời cũng bỏ luôn trường "tỉnh" đi', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang DN địa phương chi tiết; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_099.', ketQua: 'Theo thiết kế Figma', loaiTest: 'UI/UX', mucDo: 'High', thietBi: 'Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-25', bugId: 'BUG_UI_099', tester: 'Mr. Ẩn' },
  { srcRow: 229, tcId: 'TC_UI_100', reqIds: '', ycLienQuan: 'Giảm bớt layer để body hiển thị nhiều hơn ở phần bài đăng', dsIds: 'DS_03', trangLienQuan: 'DS_03: Trang DN địa phương chi tiết', tenTC: 'Xác minh lỗi BUG_UI_100', moTaTC: 'Kiểm tra Trang DN địa phương chi tiết. Hiện tượng cần xác minh: Body đang nhỏ', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang DN địa phương chi tiết; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_100.', ketQua: 'Bớt layer, body rộng hơn', loaiTest: 'UI/UX', mucDo: 'High', thietBi: 'Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-25', bugId: 'BUG_UI_100', tester: 'Mr. Ẩn' },
  { srcRow: 230, tcId: 'TC_UI_101', reqIds: 'YC_69', ycLienQuan: 'YC_69: Ứng viên gần đây', dsIds: 'DS_62', trangLienQuan: 'DS_62: Ứng viên gần đây', tenTC: 'Xác minh lỗi BUG_UI_101', moTaTC: 'Kiểm tra Ứng viên gần đây. Hiện tượng cần xác minh: - Hiển thị đúng các trường dữ liệu theo thiết kế\n- Layout tìm kiếm đúng với thiết kế\n- Avarta nhỏ lại', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Ứng viên gần đây; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_101.', ketQua: 'Đúng theo thiết kế Figma', loaiTest: 'UI/UX', mucDo: 'Critical', thietBi: 'Desktop, Tablet, Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-25', bugId: 'BUG_UI_101', tester: 'Mr. Ẩn' },
  { srcRow: 231, tcId: 'TC_UI_102', reqIds: 'YC_41', ycLienQuan: 'YC_41:  Chi tiết việc làm', dsIds: 'DS_65', trangLienQuan: 'DS_65: Trang Chi tiết việc làm', tenTC: 'Xác minh lỗi BUG_UI_102', moTaTC: 'Kiểm tra Trang Chi tiết việc làm. Hiện tượng cần xác minh: Trắng trang khi link lỗi', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Chi tiết việc làm; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_102.', ketQua: 'Xuất hiện thông báo giúp người dùng biết trạng thái của bài đăng tuyển dụng', loaiTest: 'UI/UX', mucDo: 'Critical', thietBi: 'Desktop, Tablet, Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-25', bugId: 'BUG_UI_102', tester: 'Mr. Ẩn' },
  { srcRow: 232, tcId: 'TC_UI_103', reqIds: 'YC_46', ycLienQuan: 'YC_46: Khung chat popup truy cập nhanh từ mọi trang.', dsIds: 'DS_07', trangLienQuan: 'DS_07: Khung Hộp thư + tin nhắn', tenTC: 'Xác minh lỗi BUG_FUNC_048', moTaTC: 'Kiểm tra Khung Hộp thư + tin nhắn. Hiện tượng cần xác minh: Lỗi link(404)', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Khung Hộp thư + tin nhắn; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_FUNC_048.', ketQua: 'Xuất hiện đúng link bài tuyển dụng', loaiTest: 'UI/UX', mucDo: 'Critical', thietBi: 'Desktop, Tablet, Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-25', bugId: 'BUG_FUNC_048', tester: 'Mr. Ẩn' },
  { srcRow: 233, tcId: 'TC_UI_104', reqIds: 'YC_41', ycLienQuan: 'YC_41: Chi tiết việc làm', dsIds: 'DS_65', trangLienQuan: 'DS_65: Trang Chi tiết việc làm', tenTC: 'Xác minh lỗi BUG_FUNC_049', moTaTC: 'Kiểm tra Trang Chi tiết việc làm. Hiện tượng cần xác minh: Thiếu hoặc chưa có dữ liệu cần thiết hiển thị đầy đủ vào trang', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Chi tiết việc làm; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_FUNC_049.', ketQua: 'Hiển thị đầy đủ, hoặc giải pháp tốt nhất giải quyết vấn đề', loaiTest: 'UI/UX', mucDo: 'Critical', thietBi: 'Desktop, Tablet, Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-26', bugId: 'BUG_FUNC_049', tester: 'Mr. Ẩn' },
  { srcRow: 234, tcId: 'TC_UI_105', reqIds: 'YC_41', ycLienQuan: 'YC_41: Chi tiết việc làm', dsIds: 'DS_65', trangLienQuan: 'DS_65: Trang Chi tiết việc làm', tenTC: 'Xác minh lỗi BUG_UI_103', moTaTC: 'Kiểm tra Trang Chi tiết việc làm. Hiện tượng cần xác minh: Avt, text-align, hiển thị đang sai hoặc thiếu. Xem chi tiết trong ảnh', tienDK: 'Hệ thống và dữ liệu kiểm thử sẵn sàng.', buoc: 'Mở Trang Chi tiết việc làm; thực hiện thao tác liên quan; đối chiếu kết quả; lưu bằng chứng và cập nhật BUG_ID BUG_UI_103.', ketQua: 'Đúng theo thiết kế Figma', loaiTest: 'UI/UX', mucDo: 'Critical', thietBi: 'Desktop, Tablet, Mobile', trangThai: 'Chưa bắt đầu', ngayThucHien: '2026-08-26', bugId: 'BUG_UI_103', tester: 'Mr. Ẩn' },
];

function createMissingTestCases() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var loi = ss.getSheetByName('05_Lỗi_Tester');
  var tc = ss.getSheetByName('04_Test_Cases');
  if (!loi || !tc) throw new Error('Không tìm thấy sheet 05_Lỗi_Tester hoặc 04_Test_Cases.');

  var COL_TCID_LOI = 7;   // G ở 05_Lỗi_Tester
  var tcAppendRow = tc.getLastRow() + 1;

  var created = 0, skipped = 0;
  NEW_TEST_CASES.forEach(function (d) {
    var existing = loi.getRange(d.srcRow, COL_TCID_LOI).getValue();
    if (existing && String(existing).trim() !== '') {
      skipped++;
      return; // dòng này đã có TC_ID rồi (có thể script đã chạy trước đó) -> bỏ qua, không tạo trùng
    }

    // Thêm 1 dòng mới vào 04_Test_Cases (cột A..Q)
    tc.getRange(tcAppendRow, 1, 1, 17).setValues([[
      d.tcId, d.reqIds, d.ycLienQuan, d.dsIds, d.trangLienQuan, d.tenTC, d.moTaTC,
      d.tienDK, d.buoc, d.ketQua, d.loaiTest, d.mucDo, d.thietBi, d.trangThai,
      d.ngayThucHien ? new Date(d.ngayThucHien) : '', d.bugId, d.tester
    ]]);
    if (d.ngayThucHien) tc.getRange(tcAppendRow, 15).setNumberFormat('dd/MM/yyyy');
    tcAppendRow++;

    // Ghi TC_ID vào 05_Lỗi_Tester
    loi.getRange(d.srcRow, COL_TCID_LOI).setValue(d.tcId);
    created++;
  });

  Logger.log('Đã tạo mới: ' + created + ' | Bỏ qua (đã có TC_ID từ trước): ' + skipped);
  SpreadsheetApp.getUi().alert('Hoàn tất!\nĐã tạo mới: ' + created + ' Test Case.\nBỏ qua (đã có sẵn): ' + skipped + ' dòng.');
}
